// 
// Decompiled by Procyon v0.5.36
// 

package flightsim.simconnect.recv;

public enum RecvID
{
    ID_NULL("ID_NULL", 0), 
    ID_EXCEPTION("ID_EXCEPTION", 1), 
    ID_OPEN("ID_OPEN", 2), 
    ID_QUIT("ID_QUIT", 3), 
    ID_EVENT("ID_EVENT", 4), 
    ID_EVENT_OBJECT_ADDREMOVE("ID_EVENT_OBJECT_ADDREMOVE", 5), 
    ID_EVENT_FILENAME("ID_EVENT_FILENAME", 6), 
    ID_EVENT_FRAME("ID_EVENT_FRAME", 7), 
    ID_SIMOBJECT_DATA("ID_SIMOBJECT_DATA", 8), 
    ID_SIMOBJECT_DATA_BYTYPE("ID_SIMOBJECT_DATA_BYTYPE", 9), 
    ID_WEATHER_OBSERVATION("ID_WEATHER_OBSERVATION", 10), 
    ID_CLOUD_STATE("ID_CLOUD_STATE", 11), 
    ID_ASSIGNED_OBJECT_ID("ID_ASSIGNED_OBJECT_ID", 12), 
    ID_RESERVED_KEY("ID_RESERVED_KEY", 13), 
    ID_CUSTOM_ACTION("ID_CUSTOM_ACTION", 14), 
    ID_SYSTEM_STATE("ID_SYSTEM_STATE", 15), 
    ID_CLIENT_DATA("ID_CLIENT_DATA", 16), 
    ID_EVENT_WEATHER_MODE("ID_EVENT_WEATHER_MODE", 17), 
    ID_AIRPORT_LIST("ID_AIRPORT_LIST", 18), 
    ID_VOR_LIST("ID_VOR_LIST", 19), 
    ID_NDB_LIST("ID_NDB_LIST", 20), 
    ID_WAYPOINT_LIST("ID_WAYPOINT_LIST", 21), 
    ID_EVENT_MULTIPLAYER_SERVER_STARTED("ID_EVENT_MULTIPLAYER_SERVER_STARTED", 22), 
    ID_EVENT_MULTIPLAYER_CLIENT_STARTED("ID_EVENT_MULTIPLAYER_CLIENT_STARTED", 23), 
    ID_EVENT_MULTIPLAYER_SESSION_ENDED("ID_EVENT_MULTIPLAYER_SESSION_ENDED", 24), 
    ID_EVENT_RACE_END("ID_EVENT_RACE_END", 25), 
    ID_EVENT_RACE_LAP("ID_EVENT_RACE_LAP", 26);
    
    private RecvID(final String name, final int ordinal) {
    }
    
    public static RecvID type(final int i) {
        final RecvID[] values = values();
        if (i < 0 || i > values.length) {
            return RecvID.ID_NULL;
        }
        return values[i];
    }
}
